# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gus Gita's Blog
email: wildbot110@gmail.com
description: > # A personal blog by Gus Gita.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://gusgita.github.io" # the base hostname & protocol for your site
twitter_username: gusgita
github_username:  gusgita

# Build settings
markdown: kramdown
